schemaVersion: 2.2.2
metadata:
  name: ${{values.system}}
components:
  - name: tooling-container
    container:
      image: ghcr.io/ansible/ansible-workspace-env-reference:latest
      memoryRequest: 256M
      memoryLimit: 6Gi
      cpuRequest: 250m
      cpuLimit: 2000m
      args: ["tail", "-f", "/dev/null"]
      env:
        - name: KUBEDOCK_ENABLED
          value: "true"
        - name: GIT_USER_NAME
          value: "User1"
        - name: GIT_USER_EMAIL
          value: "user1@demo.com"
commands:
  - id: configure-git
    exec:
      component: tooling-container
      commandLine: |
        git config --global user.name "${GIT_USER_NAME}"
        git config --global user.email "${GIT_USER_EMAIL}"
        echo "Git configured with name: ${GIT_USER_NAME} and email: ${GIT_USER_EMAIL}"
events:
  postStart:
    - configure-git


