---
- name: Playbook to configure ansible controller post installation
  hosts: localhost
  connection: local
  collections:
    - infra.aap_configuration
  vars:
    aap_applications:
      - name: rhdh
        organization: Default
        description: red hat developer hub
        state: "present"
        client_type: "confidential"
        authorization_grant_type: "password"
  roles:
    - install-aap-controller
    - {role: infra.aap_configuration.controller_license, ignore_errors: true }
    - configure-aap-controller
