---
- name: Playbook to configure ansible controller post installation
  hosts: localhost
  connection: local
  collections:
    - infra.aap_configuration
  vars:
    aap_applications:
      - name: rhdh
        organization: Default
        description: red hat developer hub
        state: "present"
        client_type: "confidential"
        authorization_grant_type: "password"
  tasks:
    - name: Attach to a subscription (requires fetching subscriptions at least once before)
      ansible.controller.license:
        manifest: "/Users/starnold/code/backstage/install/manifest_aap.zip"
        controller_username: admin
        controller_password: "AkGPgTNaCjQdPTEGB8JEB8wgRP7S7mAy"
        controller_host: "aap-aap.apps.cluster-29hcd.29hcd.sandbox367.opentlc.com"
