---
# tasks file for configure-aap-controller
- name: Install automation controller
  kubernetes.core.k8s:
    state: present
    src: automation-platform.yaml

- name: Wait for aap operator to install (aap-controller-task)
  kubernetes.core.k8s_info:
    namespace: aap
    kind: pod
    label_selectors:
      - app.kubernetes.io/name=aap-controller-task
    wait: true
    wait_timeout: 600
    wait_condition:
      type: Ready
      status: true



- name: Retrieve controller password 
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: aap-admin-password
    namespace: aap
  register: r_aap_password

- name: Decode aap password
  set_fact:
    aap_password: '{{ r_aap_password.resources[0].data.password | b64decode }}'


- name: Attach a subscription using the manifest file
  ansible.controller.license:
    manifest: "{{ playbook_dir }}/manifest_aap.zip"
    controller_username: admin
    controller_password: "{{ aap_password }}"
    controller_host: "{{ aap_hostname }}"
  retries: 7
  delay: 15
