- name: Promote Ansible Project Playbook
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    aap_hostname: "{{ lookup('env', 'AAP_HOSTNAME') }}"
    aap_username: "admin"
    aap_password: "{{ lookup('env', 'AAP_PASSWORD') }}"
    tag: "{{ lookup('env', 'TAG') }}"
    aap_validate_certs: "false"


  tasks:
    - name: Update production project to point to refspec
      ansible.controller.project:
        name: "${{values.system}}-prod"
        description: "${{values.system}} production project"
        organization: "Default"
        state: present
        scm_type: git
        controller_username: "{{ aap_username }}"
        controller_password: "{{ aap_password }}"
        controller_host: "{{ aap_hostname }}"
        scm_url: "https://gitlab-gitlab.apps.cluster-p74xn.p74xn.sandbox2280.opentlc.com/development/${{values.system}}.git"
        scm_branch: "{{ tag }}"
        scm_refspec: ""
      register: prod_project_result

    - name: refresh project
      ansible.controller.project_update:
        name: "${{values.system}}-prod"
        controller_username: "{{ aap_username }}"
        controller_password: "{{ aap_password }}"
        controller_host: "{{ aap_hostname }}"
