apiVersion: batch/v1
kind: Job
metadata:
  name: create-bucket
  namespace: minio
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: quay.io/minio/mc
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              export MC_CONFIG_DIR=/tmp
              mc alias set myminio http://minio.minio.svc.cluster.local:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD
              mc mb myminio/backstage-bucket || echo "Bucket already exists"
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-keys
                  key: minio_root_user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-keys
                  key: minio_root_password