kind: Service
apiVersion: v1
metadata:
  name: minio
  namespace: minio
spec:
  ports:
    - name: minio
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: console
      protocol: TCP
      port: 9001
      targetPort: 9001
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: minio