kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  
  name: minio-pv-claim
  namespace: minio
  labels:
    app: minio-storage-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Gi
  volumeMode: Filesystem