apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: gitlab-tag
  namespace: ${{values.system}}
  labels:
    operator.tekton.dev/operand-name: openshift-pipelines-addons
spec:
  params:
    - name: git-revision
      value: $(body.checkout_sha)
    - name: git-commit-message
      value: '$(body.commits[0].message)'
    - name: git-repo-url
      value: $(body.repository.git_http_url)
    - name: git-repo-name
      value: $(body.repository.name)
    - name: pusher-name
      value: $(body.user_name)
    - name: git-refspec
      value: $(body.ref)