apiVersion: v1
kind: Pod
metadata:
  name: ${{values.system}}-test-server
  namespace: ${{values.system}}
  labels:
    app: "${{values.system}}-test-server"
    playbook: "${{values.system}}"
spec:
  serviceAccountName: default
  containers:
    - name: rhel
      image: "registry.redhat.io/ubi9/ubi-init"
      workingDir: "/tmp"
      ports:
        - containerPort: 80
      #command: [ "sleep" ]
      #args: [ "infinity" ]
      #command:
      #  - "/sbin/init"
      securityContext:
        runAsUser: 0
        capabilities:
          add: ["CAP_SETFCAP"]
---
apiVersion: v1
kind: Service
metadata:
  name: "${{values.system}}-test-server"
  namespace: ${{values.system}}
  labels:
    playbook: "${{values.system}}"
spec:
  selector:
    app: ${{values.system}}-test-server
  ports:
    - protocol: TCP
      port: 80        # Service port
      targetPort: 80  # Pod container port
  type: ClusterIP     # Use NodePort or LoadBalancer to expose externally
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ${{values.system}}-test-server
  namespace: ${{values.system}}
  labels:
    playbook: "${{values.system}}"
spec:
  to:
    kind: Service
    name: ${{values.system}}-test-server
    weight: 100
  port:
    targetPort: 80
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None