apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{values.system}}-test-server
  namespace: ${{values.system}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{values.system}}-test-server
  template:
    metadata:
      labels:
        app: "${{values.system}}-test-server"
    spec:
      serviceAccountName: pipeline
      containers:
        - name: rhel
          image: "registry.redhat.io/ubi9/ubi-init"
          workingDir: "/tmp"
          ports:
            - containerPort: 80
          #command: [ "sleep" ]
          #args: [ "infinity" ]
          tmpfs:
            - /run
            - /tmp
          volumes:
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
          capabilities:
            - SYS_ADMIN
          #command:
          #  - "/sbin/init"
          pre_build_image: true
          securityContext:
            runAsUser: 0
            capabilities:
              add: ["CAP_SETFCAP"]
---
apiVersion: v1
kind: Service
metadata:
  name: "${{values.system}}-test-server"
  namespace: ${{values.system}}
spec:
  selector:
    app: ${{values.system}}-test-server
  ports:
    - protocol: TCP
      port: 80        # Service port
      targetPort: 80  # Pod container port
  type: ClusterIP     # Use NodePort or LoadBalancer to expose externally
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ${{values.system}}-test-server
  namespace: ${{values.system}} 
spec:
  to:
    kind: Service
    name: ${{values.system}}-test-server
    weight: 100
  port:
    targetPort: 80
  wildcardPolicy: None